### ISSUE TITLE
Readme States Its the Latest CLDR version, v29?

### ISSUE THREAD

**Issue by SCKelemen** [go-playground/universal-translator#13]
I can't find any hard statement saying this is a stable release, but it looks like it is to me
http://cldr.unicode.org/index/downloads/cldr-30

**Comment by joeybloggs** [comment]
@SCKelemen you are correct v30 is now the latest stable release..I was waiting to regenerate the l10n and rules for two reasons:

1. I was hoping to get some help creating tests for all locales so that I knew that regenerating with v30 wouldn't break anything https://github.com/go-playground/locales/issues/1 but only a couple of people have contributed.

2. Was waiting for a couple of point releases, which it looks like it has had now, before hand.

I will regenerate it all with v30 tomorrow https://github.com/go-playground/locales/blob/master/cmd/README.md .. it should only takes a few minutes.

**Comment by SCKelemen** [comment]
@joeybloggs Can you create more specific instructions on how I can help?

**Comment by joeybloggs** [comment]
Are you referring to this issue or #10 @SCKelemen ?

For this one I just have to download the new rules, run my locale generation code, run tests to ensure it's all still working and then update README to state using v30.

I can do this tomorrow and if all goes well won't take much time at all.

**Comment by SCKelemen** [comment]
#10

**Comment by joeybloggs** [comment]
@SCKelemen this has been updated in [Release 0.16.0](https://github.com/go-playground/universal-translator/releases/tag/v0.16.0)
